export const GET_ALL_PRODUCT_REQ = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_ERROR = "GET_ALL_PRODUCT_ERROR";

export const ALL_PRODUCTS_REQ = "ALL_PRODUCTS_REQ";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAILURE = "ALL_PRODUCTS_FAILURE";
